// Demo examples, not client commissions. Replace these with actual work later.
export const workConfig = {
  id: 'radovi',
  eyebrow: 'ODABRANI RADOVI',
  title: 'Prostor je početak. Detalji čine razliku.',
  description: 'Tri primjera kako namještaj može pratiti potrebe prostora — od odlaganja do kutka za odmor.',
  demoLabel: 'Demo primjeri rješenja',
  tabsLabel: 'Izaberite primjer rješenja',
  detailsLabel: 'DETALJI ZA RAZRADU',
  items: [
    {
      id: 'wardrobe-example',
      tabLabel: 'Garderober',
      category: 'PLAKARI I GARDEROBERI',
      title: 'Sve na svom mjestu.',
      description: 'Dobro osmišljen garderober počinje od stvari koje u njemu čuvate. Police, ladice i prostor za vješanje raspoređuju se prema vašim navikama.',
      focusLabel: 'Fokus rješenja',
      focus: 'Preglednost i iskorišten prostor',
      details: ['Raspored unutrašnjih elemenata', 'Način otvaranja vrata', 'Osvjetljenje i završna obrada'],
      image: 'wardrobe-02.jpg',
      imageAlt: 'Inspirativni primjer garderobera',
      imagePosition: 'center',
    },
    {
      id: 'living-example',
      tabLabel: 'Dnevni boravak',
      category: 'TV ZIDOVI I KOMODE',
      title: 'Prostor za mirniji dan.',
      description: 'Mjesto za televizor, tehniku i predmete koje volite. Otvoreni i zatvoreni elementi mogu povezati sve što je potrebno dnevnom boravku.',
      focusLabel: 'Fokus rješenja',
      focus: 'Sklad odlaganja i izlaganja',
      details: ['Položaj ekrana i priključaka', 'Zatvoreno odlaganje i otvorene police', 'Usklađivanje s ostatkom enterijera'],
      image: 'tv-wall-02.jpg',
      imageAlt: 'Inspirativni primjer TV zida s komodom',
      imagePosition: 'center',
    },
    {
      id: 'bathroom-example',
      tabLabel: 'Kupatilo',
      category: 'KUPATILSKI NAMJEŠTAJ',
      title: 'Više reda. Više prostora.',
      description: 'U kupatilu svaki centimetar ima svoju ulogu. Namještaj se planira oko instalacija, umivaonika i svega što želite imati pri ruci.',
      focusLabel: 'Fokus rješenja',
      focus: 'Praktičnost u svakodnevnoj upotrebi',
      details: ['Mjere prostora i položaj instalacija', 'Raspored ladica i ormarića', 'Izbor materijala za uslove u kupatilu'],
      image: 'bathroom-vanity-02.jpg',
      imageAlt: 'Inspirativni primjer kupatilskog namještaja',
      imagePosition: 'center',
    },
  ],
};
